//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookTBL()
        {
            this.ActionTBL = new HashSet<ActionTBL>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> Author { get; set; }
        public string PublicationYear { get; set; }
        public string Publisher { get; set; }
        public string Page { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActionTBL> ActionTBL { get; set; }
        public virtual AuthorTBL AuthorTBL { get; set; }
        public virtual CategoryTBL CategoryTBL { get; set; }
    }
}
