//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBLibraryEntities : DbContext
    {
        public DBLibraryEntities()
            : base("name=DBLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionTBL> ActionTBL { get; set; }
        public virtual DbSet<AuthorTBL> AuthorTBL { get; set; }
        public virtual DbSet<BookTBL> BookTBL { get; set; }
        public virtual DbSet<CategoryTBL> CategoryTBL { get; set; }
        public virtual DbSet<EmployeeTBL> EmployeeTBL { get; set; }
        public virtual DbSet<MemberTBL> MemberTBL { get; set; }
        public virtual DbSet<PenaltiesTBL> PenaltiesTBL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TillTBL> TillTBL { get; set; }
    }
}
