//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PenaltiesTBL
    {
        public int ID { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<int> Action { get; set; }
    
        public virtual ActionTBL ActionTBL { get; set; }
        public virtual MemberTBL MemberTBL { get; set; }
    }
}
